### ISSUE TITLE
Weird Redirection

### ISSUE THREAD

**Issue by msghera** [banglakit/shobdohash#4]
The link (https://github.com/banglakit/shobdohash/blob/develop/README.md#shobdohash---bengali-soundex-implementation) in the readme file which is supposed to be a pdf link is redirecting to some non-English website.

**Comment by aniruddha-adhikary** [comment]
@msghera Thanks for reporting! Will look into it ASAP.

**Comment by msghera** [comment]
I created a PR updating the link #5
